pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                label 'golang'
            }
            steps {
                sh 'cd ./devops/4-terraform; make build-lb'
            }
        }
        stage('Deploy') {
            agent {
                label 'terraform'
            }
            steps {
                sh 'cd ./devops/4-terraform; terraform init; make up'
            }
        }
    }
}
