FROM golang:1.17.2 AS builder

ADD . /workspace/

ARG target
RUN cd /workspace && make build-${target}

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

ARG target
COPY --from=builder /workspace/build/linux-amd64/${target} .

ARG target
ENV target_bin=$target
CMD ["sh", "-c", "./${target_bin}"]
