
Vagrant.configure("2") do |config|

  config.vm.define "ranchos" do |ranchos|
    ranchos.vm.box = "ubuntu/bionic64"
    ranchos.vm.provision :shell, path: "bootstrap.sh"
    ranchos.vm.network :forwarded_port, guest: 8080, host: 8081
    ranchos.vm.network :forwarded_port, guest: 8443, host: 8444
  end

end
